name: Update dependency

on:
  workflow_dispatch:
    inputs:
      monorepo_version:
        description: 'New Monorepo Version (ex. 2.50.0-alpha) (leave empty to "patch")'
        required: false

jobs:
  update_version:
    name: Update contracts-interface version
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:14.17
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Set yarn cache directory
        run: yarn config set cache-folder .yarn-cache
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .yarn-cache
            node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Update all @synthetixio/* dependency
        run: "sed -i 's/\"@synthetixio\\/\\(.*\\)\": \".*\"/\"@synthetixio\\/\\1/\": \"{{ github.event.inputs.monorepo_version }}\"' package.json"

      - run: yarn install --prefer-offline

      - name: Commit changes
        run: |
          git config --global user.email "team@synthetix.io" && git config --global user.name "Synthetix Team"
          git commit -am 'contracts-interface@${{ github.event.inputs.version }}'
          git push origin dev
